apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedidos-fast-food
  template:
    metadata:
      labels:
        app: pedidos-fast-food
    spec:
      containers:
        - name: pedidos-fast-food
          image: jackienascimento/pedidos-fast-food:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres-service:5432/bd-pedidos
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-fast-food-service
spec:
  selector:
    app: pedidos-fast-food
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
  