apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos-fast-food
  template:
    metadata:
      labels:
        app: pedidos-fast-food
    spec:
      containers:
        - name: pedidos-fast-food
          image: pedidos-k8s:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@host.docker.internal:5431/bd-pedidos
            - name: PAGAMENTO_FAST_FOOD_URL
              value: http://pagamentos-fast-food-service:8000/pagamento
            - name: PRODUCAO_FAST_FOOD_URL
              value: http://producao-fast-food-service:4000
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-fast-food-service
spec:
  selector:
    app: pedidos-fast-food
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
  